languare: node_js
branches:
  only:
  - master
node_js:
- 12
cache: yarn
script:
- yarn
- yarn build
- yarn test
- yarn lint
deploy:
  provider: npm
  skip_cleanup: true
  email: app.nakayama@gmail.com
  api_key:
    secure: PKS1Lhkoc2aEcXEzDNiuPPZfFfwj3AY021Mp29UZc3HyPrtgxGgO69h9BveUZaY7DwLH9eIlP8DNPv3etPk7AENZ/CQqyTno9v83hTymSc68C9RxlaOp/WL/LVUh96sh+3xmHPiAa8PA49GOsulPJWA1W17K3oCqkxeB5zUZoxYvyLv7ObSAG+7FTwOpOLWU0biPSUsl8sqxrCu2CAnxMWnuUKOQTkDF4sbkY3Lk23deEzNFlzV7GYkoBzrwaV0sENvH7ZFAdgBF7KCVnRg15ZbtZs4/qfXD94+RkYsXkQukfKvqA57jaSDeUE9GYRRB3xX+lPe2zuMsxqPvbudMfT7rZOdrvyEa/yCNIaZU+WqNrfBrNc8iUWCdzENjii68z/l0hcIE86jHDbE+ORg0YsZqo6CIMROnuj684q6oxzc7VITQ5KWd/YolD5cF4Lf7yL7P3zw8WWDwthbamQkYYHY3LX2rOEn6jJmmKLXEvDW83wPSaN1oMK5ZmVs5yjXF/n8G7nPFx7VYXb+EyAfiuOR2sTSm5kyPmIBx3k4wHA8NK0sLQz2sqsJx42pInbRn5UyTHnM2ykI/BxfhIeObe8MvBH23tpFaHIfCqXzqYsaPnIhJc4vrizYhbCa82on22UUFNx2nUvUrHTvgpx1JQ2ECTLywuyIrZKFZI3dVPY8=
after_deploy:
  - ./scripts/release.sh
